#Makefile generated by amake
#On Sat Feb  6 08:22:03 2021
#To print amake help use 'amake --help'.
CC=gcc
CPPC=g++
LINK=g++
SRCDIR=src
OBJDIR=obj
FLAGS=-g -Wall -std=c++11 -I/usr/include/libxml2 
LIBS=-larchive -lxml2 
OBJS=$(OBJDIR)/modcfg.o $(OBJDIR)/arc.o $(OBJDIR)/main.o $(OBJDIR)/opt.o $(OBJDIR)/utils.o 
EXEC=skyrim-pm
DATE=$(shell date +"%Y-%m-%d")

$(EXEC) : $(OBJS)
	$(LINK) $(OBJS) -o $(EXEC) $(FLAGS) $(LIBS)

$(OBJDIR)/modcfg.o: src/modcfg.cpp src/modcfg.h src/arc.h src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/modcfg.cpp -c -o $@

$(OBJDIR)/arc.o: src/arc.cpp src/arc.h src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/arc.cpp -c -o $@

$(OBJDIR)/main.o: src/main.cpp src/modcfg.h src/arc.h src/utils.h src/opt.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/main.cpp -c -o $@

$(OBJDIR)/opt.o: src/opt.cpp src/opt.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/opt.cpp -c -o $@

$(OBJDIR)/utils.o: src/utils.cpp src/utils.h src/opt.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/utils.cpp -c -o $@

$(OBJDIR)/__setup_obj_dir :
	mkdir -p $(OBJDIR)
	touch $(OBJDIR)/__setup_obj_dir

.PHONY: clean bzip release

clean :
	rm -rf $(OBJDIR)/*.o
	rm -rf $(EXEC)

bzip :
	tar -cvf "$(DATE).$(EXEC).tar" $(SRCDIR)/* Makefile
	bzip2 "$(DATE).$(EXEC).tar"

release : FLAGS +=-O3 -D_RELEASE
release : $(EXEC)

